services:
  backend:
    build: ./backend
    command: node app.js
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/ai_data
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=secretkey

  worker:
    build: ./backend
    command: node worker.js
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/ai_data
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build: ./frontend
    ports:
      - "5173:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo-data: