name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.sandhya }}" | docker login -u "${{ secrets.sandhyak23 }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.sandhyak23 }}/backend:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.sandhyak23 }}/backend:latest
